version: '2'
services:
    proshape-app:
        image: proshape
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://proshape-mysql:3306/proshape?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    proshape-mysql:
        extends:
            file: mysql.yml
            service: proshape-mysql
